name: "Test tfoperator plugin using KinD"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: engineerd/setup-kind@v0.3.0
      with:
        name: "kf-flyte"
        version: "v0.7.0"
        config: "kind/kind-config.yaml"
    
    - name: KinD Cluster Check
      run: |
        kubectl cluster-info
        kubectl get pods -n kube-system
    
    - name: Install Flyte + TF Operator
      run: |
        sleep 30
        echo "Installing TF-Operator"
        kubectl kustomize build github.com/CiscoAI/kf-dev/tree/master/deploy/kustomize/base/distributed-tf | kubectl apply -f -
        kubectl apply -f https://raw.githubusercontent.com/lyft/flyte/master/deployment/sandbox/flyte_generated.yaml
    
    #TODO(swiftdiaires): Add test for tf-operator on Flyte

